export type SomeRequired<T, K extends keyof T> = Omit<T, K> & Required<Pick<T, K>>;
export type { Comment, CommentStatus, CommentType } from './comment';
export type { Follow } from './follow';
export type { Group, ConditionJoinGroup, ConditionWriteNote, GroupStatus, PermissionReadNote, PermissionWriteNote } from './group';
export type { Like } from './like';
export type { Membership, MembershipRole } from './membership';
export type { Note, NoteStatus, NoteType, PermissionWriteComment } from './note';
export type { Notification, NotificationStatus, NotificationType } from './notification';
export type { Stock } from './stock';
export type { TagMap } from './tag-map';
export type { Tag } from './tag';
export type { User, UserStatus, UserType } from './user';
export type { Watch } from './watch';
