-- AlterTable
ALTER TABLE `group` ADD COLUMN `status` ENUM('NORMAL', 'DELETED') NOT NULL DEFAULT 'NORMAL';

-- AlterTable
ALTER TABLE `user` ADD COLUMN `status` ENUM('NORMAL', 'DELETED') NOT NULL DEFAULT 'NORMAL';
